spring:
  application:
    name: ELT-UK-ES56-MATERIAL-MASTER
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin     
  datasource:
    url: jdbc:mysql://localhost:3306/sps
    username: SMIXDBUser
    password: P@ssw0rd1!
    driver-class-name: com.mysql.jdbc.Driver 
server:
  port: 8080  
eureka:
  client:
    enabled: false
serviceaccount:
  username: servmxdev
  password: password   

activemq:
    queuename: queue:SPS-ELT-UK-MATERIAL-MASTER-DEV
          
file:
  backup:
    location: C:\\JavaTest\\SPS\\ES56_ELTUKMAP\\      
ftp:
  drop:
    location: nepps2_dev/export

---  
spring:
  profiles: dev
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin      
server:
  port: 8080  
eureka:
  client:
    enabled: false
serviceaccount:
  username: servmxdev
  password: password   

activemq:
    queuename: queue:SPS-ELT-UK-MATERIAL-MASTER-DEV
          
file:
  backup:
    location: C:\\JavaTest\\SPS\\ES56_ELTUKMAP\\      
ftp:
  drop:
    location: nepps2_dev/export